from .IUserRepository import IUserRepository
from .ICourseRepository import ICourseRepository
from .ITeacherRepository import ITeacherRepository
from .IStudentRepository import IStudentRepository
from .IEnrollmentRepository import IEnrollmentRepository
